### ISSUE TITLE
you can use https://nocaptchaai.com/demo/hcaptcha.html

### ISSUE THREAD

**Issue by 404b** [claudiofepereira/nocaptchaai-selenium#1]
https://github.com/claudiofepereira/nocaptchaai-selenium/blob/8d625a851d4d1a53c94118bde32eda329d2463b2/examples/nopecha_solver_example.py#L35

**Comment by claudiofepereira** [comment]
@404b For sure, updated :)

**Comment by 404b** [comment]
> @404b For sure, updated :)

Thanks :)
