### ISSUE TITLE
Bug with balance check when user account is free.

### ISSUE THREAD

**Issue by nullANzero** [claudiofepereira/nocaptchaai-selenium#2]
I have the following error at startup nopecha_solver_example.py

Traceback (most recent call last):
File "C:\Users\Admin\Desktop\nocaptchaai_selenium\examples\nopecha_solver_example.py", line 40, in <module>
main()
File "C:\Users\Admin\Desktop\nocaptchaai_selenium\examples\nopecha_solver_example.py", line 32, in main
captcha_solver = Solver()
^^^^^^^^
File "C:\Users\Admin\Desktop\nocaptchaai_selenium\nocaptchaai_selenium\solver.py", line 54, in%2

**Comment by claudiofepereira** [comment]
Did some changes to the code, pull again and check if the error still occurs.

**Comment by nullANzero** [comment]
I check on the free version with a working api key and specify free API_URL

However, I get the following on the output:

Response from the API didn't have necessary keys to check Balance/Remaining Solves.
No balance/requests left on your nocatpchaAI account.
No balance/requests left on your nocatpchaAI account.
No balance/requests left on your nocatpchaAI account.
(this message is repeated)

<------------------------------------------------------------->
API_KEY: str = "MY_API_KEY"
API_URL: str = "https://free.nocaptchaai.com/solve"  # Specify API URL (pro or not).
<------------------------------------------------------------->

![Error](https://user-images.githubusercontent.com/132647691/236633494-56c5a8b6-549d-451c-a090-f92b9db00538.jpg)

**Comment by nullANzero** [comment]
> Внесли некоторые изменения в код, потяните еще раз и проверьте, по-прежнему ли возникает ошибка.

P.s: there is no previous error, however, when the data is entered, another one pops up (I left the post above), and then it's not the error itself, since there is a balance check and a message... But he doesn't see a free tariff.
