### ISSUE TITLE
no longer working , please update it

### ISSUE THREAD

**Issue by COOLasHEL** [claudiofepereira/nocaptchaai-selenium#3]
hlo bro its no longer working can you **please update it** .
**i think you have to update its xpath and a little more**.
can you please update it bro or i will update it if you can tell that which variable is for what component 
like i try to update checkbox xpath but i stuck in hook_challenge ,**hook_challenge** is for what and which element of hcaptcha it represent can you please update it or can briefly tell me about this so i can mantain repo and regularly update bro
if you want to tell me my discord is **Haxzor#6121** and telegram at  **COOOLasHELL**  . you can message me anytime.
i want to use it badly please update it brother

**Comment by COOLasHEL** [comment]
hcaptcha recently update its elements class and ids it think bro

**Comment by claudiofepereira** [comment]
Updated the challenge prompt for the grid type challenge. Should be working now. If there are any new challenge prompts texts please add them in the x_CHALLENGE_PROMPTS lists and try again.
